# Enable to include message property in default response error model
#server:
#  error:
#    include-message: always

ol:
  license:
    # key: ${OL_LICENSE_KEY}
    key: eyJhbGciOiJSUzI1NiJ9.eyJwcm9kdWN0Ijoib3BlbmxlZ2FjeS1jb3JlIiwic3ViIjoib2wtaHViIiwidmFsaWRfZm9yIjo2MCwiaXNzdWVkX2F0IjoiMjAyMi0wOC0wOVQwNjoxNDo1Mi4zNDc3NDQ1NjlaIiwiZXhwaXJ5X2RhdGUiOiIyMDIyLTExLTA2VDAwOjAwOjAwWiIsImN1c3RvbWVyX25hbWUiOiJWTXdhcmUgLSBwZWx0Z3JvdGhAdm13YXJlLmNvbSIsImN1c3RvbWVyX3R5cGUiOiJUUklBTCIsImxpY2Vuc2VfdHlwZSI6IlNBQVMiLCJvYmplY3RfbGltaXRzIjp7Im1ldGhvZHMiOi0xLCJwcmVtaXVtTWV0aG9kcyI6LTEsInB1Ymxpc2hlZFByb2plY3RzIjozLCJhcGlDYWxscyI6MjAwMH0sImNvbm5lY3RvcnMiOlsiKiJdfQ.dkYqQQ3SJxh-2YJIJk5yYxIvBs2hsxGbaqJdjwohkOFgac0TtjAtFPoEft495FtSkArHrJPJZPeDtSHzUvh96YFsdSuz4--WS8Fd9eKXWHBcI0SPKvAgLmFnKeI3epbCoFBE98WCw7GaQ3UKan9UDPGBJMTKpcm4b8XD6VUkOZixbLbSiz9h8PUoOxL2XcKOGvdxv2ABLHz-IrlsRmK4V3rLPPNRBCsr2J5dhp7ZVIOFTi4qFWdcYKHvJVneBgs00wO27AyooMyHRgOYVHPeNRxfn5ts7IhchygWeG-kl8cimZJHfnhfBsihIdTr1Ph6r-T2__MjRwKqmEIjzqMe6g
  flow:
    source-provider: HUB
    hub:
      url: https://api.ol-hub.com
      # api-key: ${OL_API_KEY}
      api-key: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJqdGkiOiIyZTIzNDUwZS04ZDBkLTQzZDYtYjg5NC1hZmNmNTdlMDE3YjkiLCJ0aWQiOiI0ZGFlMGQ0YS0xMDJjLTRlMTctYTk1YS0zYTZjNzc4NjBlYjAiLCJodHRwczovL29sLnRlbmFudHMvcmVnaW9uIjoiVVMiLCJpYXQiOjE2NjA5NDMzNjYsImlzcyI6Im9sIiwic3ViIjoiYXV0aDB8NjI5ZjZjNGZhN2Q5NmUwMDZmOGJlYjMwIn0.L2h7OTs_PFpnXqTeeKXcHewiJQZInpm3XXJ-M1EfpwRkyAao1TlKqql6S5RPeEjVO985YidFJCEji7Hy2ajeu4J_PAS37uwByWL5xQjPSC9bY27mzD8MxetQdRF4JZAHYBeMVd7ROxYqtx3hn7uCqbNTCE03-138Yc8MqRfaUYGEY8Ej2dVnjZe3LOzPKFzJmS-6tsGEeZnI4cID8N_Sj2lJNcuq22o9pvL4kDSGKIxJ-FgHQADBzB0dqGEATLJcQDhp1279WJPyAaFcmMXxSMa2F1EuyuJM01sngp27GUbgbu_9_nMrm-0VZeenAq40vha9alupcmLtomt4sqIaQQ
      project-name: account-cics-microservice
    agent:
      enabled: false

---
ol:
  cics:
    project:
      accountCicsMicroserviceAccountCics:
        uriMap: /ol/demos
        baseUrl: http://mainframe.openlegacy.com
