# Enable to include message property in default response error model
#server:
#  error:
#    include-message: always

ol:
  license:
    key: eyJhbGciOiJSUzI1NiJ9.eyJwcm9kdWN0Ijoib3BlbmxlZ2FjeS1jb3JlIiwic3ViIjoib2wtaHViIiwidmFsaWRfZm9yIjo2MCwiaXNzdWVkX2F0IjoiMjAyMi0wNi0wN1QxNToxODozOS43MTA5NjEzODlaIiwiZXhwaXJ5X2RhdGUiOiIyMDIyLTA4LTA2VDE1OjE4OjM5LjcwOTMwNTMxM1oiLCJjdXN0b21lcl9uYW1lIjoiVk13YXJlIC0gcGVsdGdyb3RoQHZtd2FyZS5jb20iLCJjdXN0b21lcl90eXBlIjoiVFJJQUwiLCJsaWNlbnNlX3R5cGUiOiJTQUFTIiwib2JqZWN0X2xpbWl0cyI6eyJtZXRob2RzIjotMSwicHJlbWl1bU1ldGhvZHMiOi0xLCJwdWJsaXNoZWRQcm9qZWN0cyI6MywiYXBpQ2FsbHMiOjIwMDB9LCJjb25uZWN0b3JzIjpbIioiXX0.KDmFH6C1jZuGCAGowOsDHUxz4gSenFiHrvXIsUWYCGsv3SVwhzUpQjc1gXgQCOyFY2qH4lHC15bp_4C_CoGltHtDLAB3DZ5qodTqByXLH_JNsFiH_fU-Gp8rOModNzE87WOPOojkP1dXSzFAbdUhplMzrcsbOgQO0aI1FFXbQYeYgK3z7SOFXC3qcLJOj7QpDlqqYISYVfgSEN9FF8p83uV0x-OG0ql0_KTE2LRHGaQuWMWLMMX-3Mr-qHywNs6GfTyZ6zZgteE-pVma_EXJcQ90rbMBgSNhoqRSyD5o5D3wrYQhmonI_lkb9noJsvKP9HCKNBRcGB2u-92j169xKA
  flow:
    source-provider: HUB
    hub:
      url: https://api.ol-hub.com
      api-key: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJqdGkiOiI0Njc0MTVhYy1kMTFhLTQ0NWUtOTlmMC0zZjcyYjdhY2I1OTkiLCJ0aWQiOiI0ZGFlMGQ0YS0xMDJjLTRlMTctYTk1YS0zYTZjNzc4NjBlYjAiLCJodHRwczovL29sLnRlbmFudHMvcmVnaW9uIjoiVVMiLCJpYXQiOjE2NTczMTEyMzAsImlzcyI6Im9sIiwic3ViIjoiYXV0aDB8NjI5ZjZjNGZhN2Q5NmUwMDZmOGJlYjMwIn0.RDZlkQWl35QaA7vxcboLHOJs-2j0Vy8Te0TwP3ERBZUUcXS6be7EhjnGEvkXEM6X1uX974oBrYxcA8VAy5XJi36RkmdUT5eJDt-4IT9kL5d30SHg6HShUgsTtuUr8dDe5euG7wSJl-eTvHm4QaCh8LTRNkz9ykpgGqrDuqmQnUOMedIgmqGaWFA0kzhKlFxYRhoIr2NT1Q6qn3i8Sf-hZjASPb3q567oMjy_5jF7EjKh9tmiSTp5KxbTg-xgXasnRV7jqna2jzYJ-W2_DPJ_QGmT0b8XykvAWOju5isKuFWR1LXT9A6OCjsj-omMWhLdXxl14E86gWPF78nlKhe-UQ
      project-name: account-cics-microservice
    agent:
      enabled: false

---
# accountCicsMicroserviceAccountCics

ol:
  cics:
    project:
      accountCicsMicroserviceAccountCics:
        uriMap: /ol/demos
        baseUrl: http://mainframe.openlegacy.com

