apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: account-cics-microservice
  labels:
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: account-cics-microservice
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/PeterEltgroth/account-cics-microservice.git
      ref:
        branch: main
  # Uncomment to enable buildpack debug level logging
  # build:
  #   env:
  #   - name: BP_DEBUG
  #     value: true